### ISSUE TITLE
[Enhancement] Save edited data into datatable

### ISSUE THREAD

**Issue by braverystory** [Napat/ml_predict_patient_noshow_appointment#15]

**Comment by braverystory** [comment]
@atomgunlk Why we have to save data to DataTable and Database? or just temporarily save into DataTable then confirm to save to Database.

**Comment by atomgunlk** [comment]
Just practice 555

จริงๆแล้วต้องเซฟลง db ให้สำเร็จก่อน 
สำเร็จแล้วค่อยเพิ่ม row ใน datatable 

หรือ 

เซฟลง db ให้สำเร็จ แล้ว reload ทั้ง datatable 
ซึ่งแบบหลังมันโหลดข้อมูลเยอะเกินไป

**Comment by braverystory** [comment]
เปิด Pull request ไว้ตามนี้ครับ https://github.com/Napat/ml_predict_patient_noshow_appointment/pull/30

**Comment by Napat** [comment]
confirm closed!
