### ISSUE TITLE
[Enhancement] Fix add form and improve add Patient UI

### ISSUE THREAD

**Issue by Pisut646** [Napat/ml_predict_patient_noshow_appointment#17]
fix and update Patient field

**Comment by Pisut646** [comment]
ในส่วนช่องที่ใส่วันที่และเวลา ผมโหลด ตัว jQuery UI Datepicker มาใช้นะครับ

**Comment by Napat** [comment]
ถ้าเห็นว่าดีก็ใช้เลย

**Comment by Pisut646** [comment]
pull request : Fix add form and improve add ui
link pull request : https://github.com/Napat/ml_predict_patient_noshow_appointment/pull/22 
link my branch : https://github.com/Pisut646/ml_predict_patient_noshow_appointment/tree/fix_add_form_and_improve_add_ui
