### ISSUE TITLE
[Enhancement] del patient from db

### ISSUE THREAD

**Issue by Pisut646** [Napat/ml_predict_patient_noshow_appointment#21]
delete patient from db

**Comment by Pisut646** [comment]
pull request : Delete data in db
link pull request : https://github.com/Napat/ml_predict_patient_noshow_appointment/pull/26
link my branch : https://github.com/Pisut646/ml_predict_patient_noshow_appointment/tree/delete_data_in_db

**Comment by Napat** [comment]
Confirm merge!
