### ISSUE TITLE
[Enhancement] Search box by patient age

### ISSUE THREAD

**Issue by braverystory** [Napat/ml_predict_patient_noshow_appointment#31]
filter search by age

**Comment by braverystory** [comment]
เพิ่มเติมส่วนการ filter ด้วยอายุแล้ว โดยเพิ่มส่วน column อื่นๆไว้ด้วย อยู่ที่ pull request https://github.com/Napat/ml_predict_patient_noshow_appointment/pull/32 คับ

**Comment by Napat** [comment]
Confirm merged
